version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: habit_db
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: habit_pass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/habit_db
      DB_USER: habit_user
      DB_PASSWORD: habit_pass
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    depends_on: [db]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@habit.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  dbdata:
